proxmoxs: 
  hosts: 
    node1:
      ansible_host: 192.168.20.2
    node2:
      ansible_host: 192.168.20.3
    node3: 
      ansible_host: 192.168.20.4
servers:
  hosts:
    ml:
     ansible_host: 192.168.10.130
    backup:
      ansible_host: 192.168.20.129
    docker: 
      ansible_host: 192.168.10.3
    nas:
      ansible_host: 192.168.10.2

home_lab:
  children:
    proxmoxs:
    servers: