[servers]
docker ansible_host=192.168.10.3 ansible_user=ansible
ml ansible_host=192.168.10.130 ansible_user=ansible
nas ansible_host=192.168.10.2 ansible_user=ansible
backup ansible_host=192.168.20.129 ansible_user=ansible

[proxmoxs]
node1 ansible_host=192.168.20.2 ansible_user=ansible
node3 ansible_host=192.168.20.4 ansible_user=ansible
node2 ansible_host=192.168.20.3 ansible_user=ansible