---
- name: Update and upgrade all packages on the system
  hosts: all
  become: true
  serial: 1

  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Upgrade packages with low system priority
      ansible.builtin.command:
        cmd: nice -n 10 ionice -c 3 apt-get -y dist-upgrade
      environment:
        DEBIAN_FRONTEND: noninteractive


# runs Wednesday 20:00 in the macbook cronjob: 
# 0 20 * * 3 /opt/homebrew/bin/ansible-playbook -i /Users/utente/Documents/GitHub/Linux-/Home_Lab_Docs/03_Automation/Ansible/inventory/hosts.yml /Users/utente/Documents/GitHub/Linux-/Home_Lab_Docs/03_Automation/Ansible/playbooks/update.yml