---
- name: Update and upgrade all packages on the system
  hosts: all
  become: true

  tasks: 
    - name: update and upgrade all packages on the system
      apt:
        update_cache: true
        upgrade: dist